import type { Asset, FixedDeposit } from '../types';

export const FIXED_DEPOSITS: readonly FixedDeposit[] = [
  {
    id: 1,
    certificateNo: 'HNB/FD/2024/8841',
    bankName: 'Hatton National Bank',
    branch: 'Colombo 06',
    principal: 500_000,
    interestRate: 12.5,
    placedOn: '2024-01-15',
    maturesOn: '2027-01-15',
    tenureMonths: 36,
    interestPayout: 'quarterly',
    fundId: 1,
    status: 'active',
    renewedFromId: null,
    notes: 'Corpus deposit. Interest credited to the general fund quarterly.',
  },
  {
    id: 2,
    certificateNo: 'BOC/FD/2025/1207',
    bankName: 'Bank of Ceylon',
    branch: 'Jaffna Main',
    principal: 300_000,
    interestRate: 11.75,
    placedOn: '2025-06-01',
    maturesOn: '2026-12-01',
    tenureMonths: 18,
    interestPayout: 'on-maturity',
    fundId: 3,
    status: 'active',
    renewedFromId: null,
    notes: 'Thiruppani reserve, to be drawn for the gopuram third stage.',
  },
  {
    id: 3,
    certificateNo: 'PB/FD/2025/4419',
    bankName: "People's Bank",
    branch: 'Nallur',
    principal: 250_000,
    interestRate: 11.0,
    placedOn: '2025-09-20',
    maturesOn: '2026-09-20',
    tenureMonths: 12,
    interestPayout: 'on-maturity',
    fundId: 2,
    status: 'active',
    renewedFromId: null,
    notes: null,
  },
  {
    id: 4,
    certificateNo: 'HNB/FD/2025/6620',
    bankName: 'Hatton National Bank',
    branch: 'Colombo 06',
    principal: 150_000,
    interestRate: 10.5,
    placedOn: '2025-11-10',
    maturesOn: '2026-11-10',
    tenureMonths: 12,
    interestPayout: 'monthly',
    fundId: 4,
    status: 'active',
    renewedFromId: null,
    notes: 'Annadhanam endowment from the Ganesan family.',
  },
  {
    id: 5,
    certificateNo: 'BOC/FD/2024/0918',
    bankName: 'Bank of Ceylon',
    branch: 'Jaffna Main',
    principal: 200_000,
    interestRate: 10.0,
    placedOn: '2024-03-01',
    maturesOn: '2025-09-01',
    tenureMonths: 18,
    interestPayout: 'on-maturity',
    fundId: 1,
    status: 'renewed',
    renewedFromId: null,
    notes: 'Matured September 2025 and rolled into BOC/FD/2025/1207.',
  },
  {
    id: 6,
    certificateNo: 'PB/FD/2023/2210',
    bankName: "People's Bank",
    branch: 'Nallur',
    principal: 120_000,
    interestRate: 9.5,
    placedOn: '2023-04-01',
    maturesOn: '2025-04-01',
    tenureMonths: 24,
    interestPayout: 'on-maturity',
    fundId: 3,
    status: 'closed',
    renewedFromId: null,
    notes: 'Closed on maturity; proceeds drawn for the well restoration.',
  },
];

export const ASSETS: readonly Asset[] = [
  {
    id: 1,
    tag: 'LB-001',
    name: 'Temple Land — Main Premises',
    nameTa: 'ஆலய நிலம் — பிரதான வளாகம்',
    category: 'land-building',
    acquiredOn: '1998-05-12',
    cost: 4_200_000,
    depreciationRate: 0,
    location: 'Nallur, Jaffna',
    condition: 'good',
    status: 'in-use',
    fundId: 1,
    disposedOn: null,
    disposalValue: null,
    notes: 'Held at cost. Land is not depreciated.',
  },
  {
    id: 2,
    tag: 'LB-002',
    name: 'Main Shrine & Mandapam',
    nameTa: 'மூலஸ்தானம் மற்றும் மண்டபம்',
    category: 'land-building',
    acquiredOn: '2004-08-20',
    cost: 3_600_000,
    depreciationRate: 2,
    location: 'Temple premises',
    condition: 'good',
    status: 'in-use',
    fundId: 1,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 3,
    tag: 'JW-001',
    name: 'Gold Kavasam — Moolavar',
    nameTa: 'தங்கக் கவசம் — மூலவர்',
    category: 'jewellery',
    acquiredOn: '2015-02-14',
    cost: 1_850_000,
    depreciationRate: 0,
    location: 'Temple strong room',
    condition: 'good',
    status: 'in-storage',
    fundId: 1,
    disposedOn: null,
    disposalValue: null,
    notes: 'Brought out for the annual festival and Vaikasi Visakam only.',
  },
  {
    id: 4,
    tag: 'JW-002',
    name: 'Silver Prabhavali',
    nameTa: 'வெள்ளிப் பிரபாவளி',
    category: 'jewellery',
    acquiredOn: '2019-06-08',
    cost: 640_000,
    depreciationRate: 0,
    location: 'Temple strong room',
    condition: 'good',
    status: 'in-storage',
    fundId: 3,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 5,
    tag: 'VH-001',
    name: 'Wooden Ther (Chariot)',
    nameTa: 'மரத் தேர்',
    category: 'vahanam',
    acquiredOn: '2009-06-25',
    cost: 1_250_000,
    depreciationRate: 5,
    location: 'Ther shed',
    condition: 'needs-repair',
    status: 'under-repair',
    fundId: 3,
    disposedOn: null,
    disposalValue: null,
    notes: 'Wheel axle and canopy timbers to be replaced before the 2027 festival.',
  },
  {
    id: 6,
    tag: 'VH-002',
    name: 'Silver Rishaba Vahanam',
    nameTa: 'வெள்ளி ரிஷப வாகனம்',
    category: 'vahanam',
    acquiredOn: '2012-11-03',
    cost: 480_000,
    depreciationRate: 0,
    location: 'Vahanam room',
    condition: 'fair',
    status: 'in-use',
    fundId: 3,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 7,
    tag: 'VS-001',
    name: 'Brass Abhishekam Vessels (set of 12)',
    nameTa: 'பித்தளை அபிஷேகப் பாத்திரங்கள்',
    category: 'vessels',
    acquiredOn: '2021-03-18',
    cost: 185_000,
    depreciationRate: 10,
    location: 'Sanctum store',
    condition: 'good',
    status: 'in-use',
    fundId: 1,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 8,
    tag: 'VS-002',
    name: 'Annadhanam Cooking Vessels',
    nameTa: 'அன்னதானச் சமையல் பாத்திரங்கள்',
    category: 'vessels',
    acquiredOn: '2022-07-05',
    cost: 142_000,
    depreciationRate: 10,
    location: 'Dining hall kitchen',
    condition: 'fair',
    status: 'in-use',
    fundId: 4,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 9,
    tag: 'FN-001',
    name: 'Dining Hall Tables & Benches',
    nameTa: 'உணவு மண்டப மேசைகள்',
    category: 'furniture',
    acquiredOn: '2020-01-22',
    cost: 210_000,
    depreciationRate: 12.5,
    location: 'Dining hall',
    condition: 'fair',
    status: 'in-use',
    fundId: 4,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 10,
    tag: 'FN-002',
    name: 'Office Furniture',
    nameTa: 'அலுவலக மரச்சாமான்கள்',
    category: 'furniture',
    acquiredOn: '2023-04-11',
    cost: 96_000,
    depreciationRate: 12.5,
    location: 'Temple office',
    condition: 'good',
    status: 'in-use',
    fundId: 1,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 11,
    tag: 'EQ-001',
    name: 'Diesel Generator 15 kVA',
    nameTa: 'டீசல் மின்னாக்கி',
    category: 'equipment',
    acquiredOn: '2021-09-30',
    cost: 385_000,
    depreciationRate: 15,
    location: 'Generator room',
    condition: 'needs-repair',
    status: 'under-repair',
    fundId: 1,
    disposedOn: null,
    disposalValue: null,
    notes: 'Serviced August 2026 — see PV-2026-0090.',
  },
  {
    id: 12,
    tag: 'EQ-002',
    name: 'Public Address System',
    nameTa: 'ஒலிபெருக்கி அமைப்பு',
    category: 'equipment',
    acquiredOn: '2022-12-02',
    cost: 168_000,
    depreciationRate: 20,
    location: 'Mandapam',
    condition: 'good',
    status: 'in-use',
    fundId: 2,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 13,
    tag: 'EQ-003',
    name: 'Festival Lighting Sets',
    nameTa: 'திருவிழா ஒளியமைப்பு',
    category: 'equipment',
    acquiredOn: '2024-05-16',
    cost: 224_000,
    depreciationRate: 20,
    location: 'Festival store',
    condition: 'good',
    status: 'in-storage',
    fundId: 2,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 14,
    tag: 'VC-001',
    name: 'Temple Van',
    nameTa: 'ஆலய வாகனம்',
    category: 'vehicle',
    acquiredOn: '2018-10-09',
    cost: 2_100_000,
    depreciationRate: 15,
    location: 'Temple garage',
    condition: 'fair',
    status: 'in-use',
    fundId: 1,
    disposedOn: null,
    disposalValue: null,
    notes: null,
  },
  {
    id: 15,
    tag: 'EQ-004',
    name: 'Old Sound Amplifier',
    nameTa: 'பழைய ஒலிபெருக்கி',
    category: 'equipment',
    acquiredOn: '2014-02-20',
    cost: 74_000,
    depreciationRate: 20,
    location: '—',
    condition: 'unusable',
    status: 'disposed',
    fundId: 1,
    disposedOn: '2026-04-30',
    disposalValue: 6_500,
    notes: 'Sold as scrap after the new PA system was commissioned.',
  },
];
