import type {
  EventType,
  EventTypeSponsor,
  SponsorUser,
  TempleEvent,
} from '../types';

const NOW = '2026-01-12T09:00:00';

export const EVENT_TYPES: readonly EventType[] = [
  {
    id: 1,
    name: 'திருவிழா',
    nameEn: 'Thiruvizha',
    frequencyType: 'multi_day',
    noOfInstances: 12,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 2,
    name: 'வைகாசி விசாக சிறப்பு பூஜை',
    nameEn: 'Vaikasi Visakam Special Pooja',
    frequencyType: 'annual',
    noOfInstances: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 3,
    name: 'நவராத்திரி விழா',
    nameEn: 'Navarathiri Festival',
    frequencyType: 'multi_day',
    noOfInstances: 9,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 4,
    name: 'சங்கடஹர சதுர்த்தி',
    nameEn: 'Sankatahara Chaturthi',
    frequencyType: 'monthly_once',
    noOfInstances: 1,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 5,
    name: 'வெள்ளிக்கிழமை பூஜை',
    nameEn: 'Friday Pooja',
    frequencyType: 'weekly',
    noOfInstances: 52,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 6,
    name: 'பிரதோஷ பூஜை',
    nameEn: 'Pradosham Pooja',
    frequencyType: 'monthly_twice',
    noOfInstances: 2,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const SPONSOR_USERS: readonly SponsorUser[] = [
  {
    id: 'usr_101',
    fullName: 'ம. கணேசன் மற்றும் குடும்பத்தினர்',
    email: 'ganesan@example.com',
    phone: '077 111 2222',
    address: 'நல்லூர், யாழ்ப்பாணம்',
  },
  {
    id: 'usr_102',
    fullName: 'செல்வி. அபிராமி இராமநாதன்',
    email: 'abirami@example.com',
    phone: '077 333 4444',
    address: 'வெள்ளவத்தை, கொழும்பு',
  },
  {
    id: 'usr_103',
    fullName: 'திருமதி. ஜெகதீஸ்வரி நடராஜா',
    email: 'jagadheswari@example.com',
    phone: '071 666 7777',
    address: 'மட்டக்களப்பு நகர்',
  },
  {
    id: 'usr_104',
    fullName: 'கார்த்திகேயன் அறக்கட்டளை',
    email: 'karthi.trust@example.com',
    phone: '021 222 9999',
    address: 'பருத்தித்துறை',
  },
  {
    id: 'usr_105',
    fullName: 'சிவஸ்ரீ குடும்பம்',
    email: 'sivashree@example.com',
    phone: '077 555 8888',
    address: 'திருநெல்வேலி, யாழ்ப்பாணம்',
  },
  {
    id: 'usr_106',
    fullName: 'ஸ்ரீ நந்திகேஸ்வரர் மன்றம்',
    email: 'nandi@example.com',
    phone: '072 444 5555',
    address: 'கொழும்பு 06',
  },
];

export const EVENT_TYPE_SPONSORS: readonly EventTypeSponsor[] = [
  {
    id: 1,
    eventTypeId: 1,
    instanceIdentifier: 10,
    customInstanceName: 'சப்பரம்',
    userId: 'usr_101',
    createdAt: NOW,
  },
  {
    id: 2,
    eventTypeId: 1,
    instanceIdentifier: 11,
    customInstanceName: 'தேர்த் திருவிழா',
    userId: 'usr_102',
    createdAt: NOW,
  },
  {
    id: 3,
    eventTypeId: 1,
    instanceIdentifier: 12,
    customInstanceName: 'தீர்த்தத் திருவிழா',
    userId: 'usr_104',
    createdAt: NOW,
  },
  {
    id: 4,
    eventTypeId: 2,
    instanceIdentifier: 1,
    customInstanceName: null,
    userId: 'usr_102',
    createdAt: NOW,
  },
  {
    id: 5,
    eventTypeId: 3,
    instanceIdentifier: 1,
    customInstanceName: 'முதலாம் நாள் பூஜை',
    userId: 'usr_101',
    createdAt: NOW,
  },
  {
    id: 6,
    eventTypeId: 3,
    instanceIdentifier: 3,
    customInstanceName: 'மூன்றாம் நாள் பூஜை',
    userId: 'usr_105',
    createdAt: NOW,
  },
  {
    id: 7,
    eventTypeId: 4,
    instanceIdentifier: 1,
    customInstanceName: null,
    userId: 'usr_103',
    createdAt: NOW,
  },
  {
    id: 8,
    eventTypeId: 5,
    instanceIdentifier: 24,
    customInstanceName: null,
    userId: 'usr_106',
    createdAt: NOW,
  },
  {
    id: 9,
    eventTypeId: 6,
    instanceIdentifier: 1,
    customInstanceName: 'வளர்பிறை பிரதோஷம்',
    userId: 'usr_106',
    createdAt: NOW,
  },
  {
    id: 10,
    eventTypeId: 6,
    instanceIdentifier: 2,
    customInstanceName: 'தேய்பிறை பிரதோஷம்',
    userId: 'usr_104',
    createdAt: NOW,
  },
];

export const TEMPLE_EVENTS: readonly TempleEvent[] = [
  {
    id: 1,
    eventTypeId: 5,
    instanceIdentifier: 2,
    customInstanceName: null,
    scheduledDate: '2026-01-09',
    startTime: '07:00',
    endTime: '08:30',
    sponsorId: 'usr_106',
    notes: 'காலை அபிஷேகம் முடிந்ததும் அன்னதானம்',
    isCompleted: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 2,
    eventTypeId: 4,
    instanceIdentifier: 1,
    customInstanceName: null,
    scheduledDate: '2026-01-27',
    startTime: '18:00',
    endTime: '20:00',
    sponsorId: 'usr_103',
    notes: null,
    isCompleted: true,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 3,
    eventTypeId: 6,
    instanceIdentifier: 1,
    customInstanceName: 'வளர்பிறை பிரதோஷம்',
    scheduledDate: '2026-02-14',
    startTime: '17:30',
    endTime: '19:00',
    sponsorId: 'usr_106',
    notes: null,
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 4,
    eventTypeId: 6,
    instanceIdentifier: 2,
    customInstanceName: 'தேய்பிறை பிரதோஷம்',
    scheduledDate: '2026-02-28',
    startTime: '17:30',
    endTime: '19:00',
    sponsorId: null,
    notes: 'அபிஷேகப் பொருட்கள் இன்னும் உறுதி செய்யப்படவில்லை',
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 5,
    eventTypeId: 5,
    instanceIdentifier: 12,
    customInstanceName: null,
    scheduledDate: '2026-03-20',
    startTime: '07:00',
    endTime: '08:30',
    sponsorId: 'usr_101',
    notes: null,
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 6,
    eventTypeId: 2,
    instanceIdentifier: 1,
    customInstanceName: null,
    scheduledDate: '2026-05-31',
    startTime: '06:30',
    endTime: '11:00',
    sponsorId: 'usr_102',
    notes: 'விசேட அபிஷேகம் மற்றும் மகா தீபாராதனை',
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 7,
    eventTypeId: 1,
    instanceIdentifier: 1,
    customInstanceName: 'கொடியேற்றம்',
    scheduledDate: '2026-06-15',
    startTime: '06:00',
    endTime: '10:00',
    sponsorId: null,
    notes: 'கொடியேற்றம் காலை 07:30 மணிக்கு',
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 8,
    eventTypeId: 1,
    instanceIdentifier: 10,
    customInstanceName: 'சப்பரம்',
    scheduledDate: '2026-06-24',
    startTime: '17:00',
    endTime: '21:00',
    sponsorId: 'usr_101',
    notes: null,
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 9,
    eventTypeId: 1,
    instanceIdentifier: 11,
    customInstanceName: 'தேர்த் திருவிழா',
    scheduledDate: '2026-06-25',
    startTime: '06:00',
    endTime: '13:00',
    sponsorId: 'usr_102',
    notes: 'வடம்பிடித்தல் காலை 07:30 மணிக்கு ஆரம்பமாகும்',
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 10,
    eventTypeId: 1,
    instanceIdentifier: 12,
    customInstanceName: 'தீர்த்தத் திருவிழா',
    scheduledDate: '2026-06-26',
    startTime: '05:30',
    endTime: '12:00',
    sponsorId: 'usr_104',
    notes: null,
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 11,
    eventTypeId: 5,
    instanceIdentifier: 24,
    customInstanceName: null,
    scheduledDate: '2026-09-18',
    startTime: '07:00',
    endTime: '08:30',
    sponsorId: 'usr_106',
    notes: 'காலை அபிஷேகம் முடிந்ததும் அன்னதானம் நடைபெறும்',
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 12,
    eventTypeId: 3,
    instanceIdentifier: 1,
    customInstanceName: 'முதலாம் நாள் பூஜை',
    scheduledDate: '2026-10-10',
    startTime: '18:30',
    endTime: '20:00',
    sponsorId: 'usr_101',
    notes: null,
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 13,
    eventTypeId: 3,
    instanceIdentifier: 3,
    customInstanceName: 'மூன்றாம் நாள் பூஜை',
    scheduledDate: '2026-10-12',
    startTime: '18:30',
    endTime: '20:00',
    sponsorId: 'usr_105',
    notes: 'சிறப்பு அலங்காரம் மற்றும் அம்மன் ஆராதனை',
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 14,
    eventTypeId: 3,
    instanceIdentifier: 9,
    customInstanceName: 'விஜயதசமி',
    scheduledDate: '2026-10-18',
    startTime: '17:00',
    endTime: '20:30',
    sponsorId: null,
    notes: null,
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 15,
    eventTypeId: 4,
    instanceIdentifier: 1,
    customInstanceName: null,
    scheduledDate: '2026-11-27',
    startTime: '18:00',
    endTime: '20:00',
    sponsorId: 'usr_103',
    notes: null,
    isCompleted: false,
    createdAt: NOW,
    updatedAt: NOW,
  },
];
