name: Sync to Deployment Fork
on:
  push:
    branches:
      - main
jobs:
  push-to-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Org Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Personal Fork
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          git remote add fork https://x-access-token:${{ secrets.SYNC_TO_FORK_TOKEN }}@github.com/Keeththi2003/np-frontend.git
          
          git push fork main --force